### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by mgifford** [CivicActions/openacr-editor#14]
On the bottom, describe what the license that the work as a whole is distributed under.  See here for licensing information...

It is in the License file, but there should be a sentence with a link.

**Comment by dmundra** [comment]
@mgifford would #16 cover this as well?

**Comment by mgifford** [comment]
No. Least not completely.

The project README should lead a user to the LICENSE.md which should link to the remote package license file that you've linked to here [https://github.com/CivicActions/openacr-editor/blob/license-tracking/license/licenses.txt](https://github.com/CivicActions/openacr-editor/blob/license-tracking/license/licenses.txt)

We just can't assume someone is going to dig for it. Just want to make it easy to make sure that everyone knows where this is.

**Comment by dmundra** [comment]
@mgifford good point. I updated those files as well to match the `openacr` setup.
