### ISSUE TITLE
Can't exclude AAA in 2.1

### ISSUE THREAD

**Issue by mgifford** [CivicActions/openacr-editor#19]
I've excluded this:
<img width="875" alt="Screenshot of editor" src="https://github.com/CivicActions/openacr-editor/assets/116832/72636b4f-fb71-41c1-995c-3b1cb47be1d7">

But they keep showing up In the header:
<img width="757" alt="Screenshot header" src="https://github.com/CivicActions/openacr-editor/assets/116832/f6cadb9a-6409-40ff-9a5f-d4984446d755">

and in the report:
<img width="1189" alt="Screenshot summary" src="https://github.com/CivicActions/openacr-editor/assets/116832/694476e2-b1eb-471d-aa28-f7bf6f083d8c">

**Comment by dmundra** [comment]
@mgifford I believe it is related to #12. Can you chime in there if you a thought about the question I posed?

**Comment by mgifford** [comment]
Yes, I think we can close this as a related issue.
