### ISSUE TITLE
Report HTML: Add summary info above each table for level A, AA, and AAA

### ISSUE THREAD

**Issue by maggiewachs** [CivicActions/openacr-editor#2]
Suggested format, where each number is dynamically generated:

Conformance to the **30** WCAG Level A criteria listed below is distributed as follows:

**9** criteria did not apply to the sample
**1** was not supported
**9** were partially supported
**11** were supported

**Comment by dmundra** [comment]
Currently in the PR the example output looks like:

> Conformance to the 30 criteria listed below is distributed as follows:
> 
> - 57 supports.
> - 4 partially supports.
> - 5 does not support.
> - 34 not applicable.
> - 0 not evaluated.

I do want to add some tests as well. ✔️
